language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo clippy --all-targets --all-features -- -D warnings
